# Generated by Django 3.1 on 2020-08-17 03:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isAuthor', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Toon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=30)),
                ('genre', models.CharField(max_length=30)),
                ('url', models.TextField()),
                ('detail', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='images/')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Restory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapterNum', models.IntegerField()),
                ('detail', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('toonID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.toon')),
            ],
        ),
        migrations.CreateModel(
            name='CharactersPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posX', models.FloatField()),
                ('posY', models.FloatField()),
                ('chapterID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restory', to='mainApp.restory')),
                ('toonID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.toon')),
            ],
        ),
        migrations.CreateModel(
            name='Characters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ImageField(upload_to='images/')),
                ('name', models.CharField(max_length=30)),
                ('detail', models.TextField()),
                ('toonID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.toon')),
            ],
        ),
    ]
